### ISSUE TITLE
Create user story #2

### ISSUE THREAD

**Issue by johnserraon** [visualizing-your-future/visualizing-your-future#2]
Do all work for this task in a branch called issue-02

Create user story #2 in the GitHub discussions tab of the visualizing-your-future repo. (2 required total for M1)
User story examples: https://courses.ics.hawaii.edu/ics414f24/modules/module-requirements-elicitation/

**Comment by GalenChang** [comment]
https://github.com/orgs/visualizing-your-future/discussions/16
