### ISSUE TITLE
Implement home page

### ISSUE THREAD

**Issue by vavalverde** [visualizing-your-future/visualizing-your-future#21]
Do all work for this task in a branch called issue-21

Create a home page for a signed in user (not admin).

-user profile display
-important information
-list of projections available

**Comment by johnserraon** [comment]
Created home page for logged in user with navbar entry and preliminary layout for future direction. Will have to pull information from databases to display client details, projections, etc. once those are added.
![Image](https://github.com/user-attachments/assets/e49ee9be-04d9-4ec8-ac60-d85b6917a5ad)
