### ISSUE TITLE
Create Testcafe

### ISSUE THREAD

**Issue by vavalverde** [visualizing-your-future/visualizing-your-future#23]
Do all work for this task in a branch called issue-23

Create test for M! to ensure all pages are accessible from navbar or buttons.
-Login page
-Signout page
-visualization page
-register page
(to be continued)

**Comment by johnserraon** [comment]
Might be better to split this up into multiple issue tickets, even if you end up doing the rest of them

**Comment by hoangtng** [comment]
Having done so far

 √ Test that landing page shows up
 √ Test that signin and signout work
 √ Test that user pages show up
 √ Test that sign up for accountant and sign out work
 √ Test that sign up for client and sign out work
 √ Test that admin pages show up

**Comment by hoangtng** [comment]
> Might be better to split this up into multiple issue tickets, even if you end up doing the rest of them. I saw some tests completed and it'd be good to show you did those already (vs. having to finish _all_ of them to show you did any of them! This happened in my last project)

I agree, the testing is not too complex in our M1 ( just showing up the pages ). But the next issues, we should split it up to write multiple test for each functional.
