### ISSUE TITLE
Clean up repo of unused assets, pages, references

### ISSUE THREAD

**Issue by vavalverde** [visualizing-your-future/visualizing-your-future#35]
Do all work for this task in a branch called issue-35

- Remove /clientData mockup page since it is superseded by /clientDataImport
- Remove AddStuff, ListStuff assets and elements
- Tidy up anything else that's noticed

**Comment by johnserraon** [comment]
Will probably add other cleanup items to this task

**Comment by johnserraon** [comment]
Updated task to a general clean-up task

**Comment by johnserraon** [comment]
Clean-up pass completed, will do a local run-through of site before finalizing + merge.
- Deleted \doc directory default images, may be nice to replace them later on with our site images
- Need to verify again whether we are keeping /dataInput since the page was overhauled I believe
