### ISSUE TITLE
Implement admin ability to delete user accounts

### ISSUE THREAD

**Issue by janeljo** [visualizing-your-future/visualizing-your-future#72]
Do all work in branch named issue-72.

Update page EditProfile.jsx that will allow the admin to delete user accounts.

**Comment by GalenChang** [comment]
The flow of calls is as follows:

AdminProfileCollection.removeIt() and UserProfileCollection.removeIt() call
BaseProfileCollection.removeIt(), which calls
Meteor.users.remove() and BaseCollection.removeIt().

The last 2 calls have access denied issues.  Will ask professor for help.
